name: pr-opened

on:
  pull_request:
    types: [opened]

jobs:
  mark-as-draft:
    name: Mark as draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Mark as draft
        env: {GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'}
        run: gh pr ready ${{ github.event.pull_request.number }} --undo
